"""gen_validate_script.py

Generates a self-contained Lua validation script with mq-definitions data
baked in. The Lua script runs entirely in-game, compares each type's runtime
members against the embedded defs, and writes a JSON result file.

Usage:
    python scripts/gen_validate_script.py

After running:
    1. /lua run validate-defs   (in-game)
    2. python scripts/gen_validate_script.py --report   (generates markdown)
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from config import load_config
from mq_definitions import parse_definitions

# Where the generated Lua script and its output file land
SCRIPT_NAME   = "validate-defs.lua"
RESULT_NAME   = "validate-defs-result.json"
REPORT_DIR    = Path(__file__).parent.parent / "validation"


LUA_TEMPLATE = """\
-- validate-defs.lua
-- Auto-generated by scripts/gen_validate_script.py — do not edit.
-- Run with: /lua run validate-defs
--
-- Compares runtime MQ type members against baked-in mq-definitions data,
-- then writes results to validate-defs-result.json in the lua directory.

local mq = require('mq')

-- ---------------------------------------------------------------------------
-- Baked-in mq-definitions data: {type_name -> {member -> true}}
-- ---------------------------------------------------------------------------
local defs = {DEF_TABLE}

-- ---------------------------------------------------------------------------
-- Minimal JSON encoder
-- ---------------------------------------------------------------------------
local function je(v)
    local t = type(v)
    if t == 'string'  then return '"' .. v:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"') .. '"' end
    if t == 'boolean' then return tostring(v) end
    if t == 'number'  then return tostring(v) end
    if t == 'nil'     then return 'null' end
    if t == 'table' then
        if #v > 0 then
            local p = {}
            for _, x in ipairs(v) do p[#p+1] = je(x) end
            return '[' .. table.concat(p, ',') .. ']'
        else
            local p = {}
            for k, x in pairs(v) do p[#p+1] = je(tostring(k)) .. ':' .. je(x) end
            return '{' .. table.concat(p, ',') .. '}'
        end
    end
    return 'null'
end

-- ---------------------------------------------------------------------------
-- Scan and compare
-- ---------------------------------------------------------------------------
local results = {}
local type_list = {}
for k in pairs(defs) do type_list[#type_list+1] = k end
table.sort(type_list)

local total = #type_list
print(string.format('[validate-defs] Checking %d types...', total))

for idx, type_name in ipairs(type_list) do
    local def_members = defs[type_name]
    local tlo = mq.TLO.Type(type_name)

    if not tlo() then
        results[type_name] = { exists=false }
    else
        -- Scan runtime members (index loop, early-stop)
        local runtime = {}
        local empty_run = 0
        for i = 0, 300 do
            local m = tlo.Member(i)()
            if m and m ~= '' then
                runtime[m:lower()] = true
                empty_run = 0
            else
                empty_run = empty_run + 1
                if empty_run >= 20 then break end
            end
        end

        -- What's in-game but not documented
        local missing = {}
        for m in pairs(runtime) do
            if not def_members[m] then missing[#missing+1] = m end
        end
        table.sort(missing)

        -- What's documented but not in-game
        local stale = {}
        for m in pairs(def_members) do
            if not runtime[m] then stale[#stale+1] = m end
        end
        table.sort(stale)

        local inherits = tlo.InheritedType and tlo.InheritedType() or nil
        local rc = 0
        for _ in pairs(runtime) do rc = rc + 1 end
        local dc = 0
        for _ in pairs(def_members) do dc = dc + 1 end

        results[type_name] = {
            exists         = true,
            runtime_count  = rc,
            def_count      = dc,
            missing        = missing,
            stale          = stale,
            inherits       = (inherits and inherits ~= '') and inherits or nil,
        }
    end

    if idx % 10 == 0 then
        print(string.format('[validate-defs] %d/%d done', idx, total))
    end
    mq.delay(300)
end

-- ---------------------------------------------------------------------------
-- Write JSON output
-- ---------------------------------------------------------------------------
local out_path = mq.luaDir .. '/{result_name}'
local f, err = io.open(out_path, 'w')
if f then
    f:write(je(results))
    f:close()
    print('[validate-defs] Done! Results written to ' .. out_path)
    print('[validate-defs] Now run: python scripts/gen_validate_script.py --report')
else
    print('[validate-defs] ERROR writing output: ' .. tostring(err))
end
"""


def build_def_table(defs: dict[str, set[str]]) -> str:
    """Render the defs dict as a Lua table literal."""
    lines = ["{"]
    for type_name in sorted(defs):
        members = sorted(defs[type_name])
        if not members:
            continue
        member_str = ", ".join(f'["{m}"]=true' for m in members)
        lines.append(f'  ["{type_name}"] = {{{member_str}}},')
    lines.append("}")
    return "\n".join(lines)


def generate_lua(cfg, defs: dict) -> str:
    def_table = build_def_table(defs)
    script = LUA_TEMPLATE.replace("{DEF_TABLE}", def_table)
    script = script.replace("{result_name}", RESULT_NAME)
    return script


def generate_reports(cfg):
    result_path = cfg.mq_lua_path / RESULT_NAME
    if not result_path.exists():
        print(f"Result file not found: {result_path}")
        print("Run /lua run validate-defs in-game first.")
        return

    data = json.loads(result_path.read_text(encoding="utf-8"))
    REPORT_DIR.mkdir(exist_ok=True)

    summary_rows = []

    for type_name in sorted(data):
        info = data[type_name]
        md_path = REPORT_DIR / f"{type_name}.md"

        with md_path.open("w", encoding="utf-8") as f:
            f.write(f"# {type_name}\n\n")

            if not info.get("exists", True):
                # Skip types not registered at runtime — not useful to report
                continue

            inherits      = info.get("inherits")
            runtime_count = info.get("runtime_count", 0)
            def_count     = info.get("def_count", 0)
            missing       = info.get("missing") or []
            stale         = info.get("stale") or []
            matched       = runtime_count - len(missing)

            if inherits:
                f.write(f"**Inherits:** `{inherits}`\n\n")

            f.write("| | Count |\n|---|---|\n")
            f.write(f"| Runtime members | {runtime_count} |\n")
            f.write(f"| Documented members | {def_count} |\n")
            f.write(f"| Matched | {matched} |\n")
            f.write(f"| Missing from defs | {len(missing)} |\n")
            f.write(f"| Stale in defs | {len(stale)} |\n\n")

            if missing:
                f.write("## Missing from mq-definitions\n\n")
                f.write("In-game but no `@field` in the definitions.\n\n")
                for m in missing:
                    f.write(f"- `{m}`\n")
                f.write("\n")

            if stale:
                f.write("## Stale in mq-definitions\n\n")
                f.write("`@field` entries in definitions not found at runtime.\n\n")
                for m in stale:
                    f.write(f"- `{m}`\n")
                f.write("\n")

            if not missing and not stale:
                f.write("> All documented members matched at runtime.\n\n")

        summary_rows.append((
            type_name, runtime_count, def_count,
            len(missing), len(stale),
            "ok" if not missing and not stale else "gaps"
        ))

    # Write summary index
    summary_path = REPORT_DIR / "_summary.md"
    with summary_path.open("w", encoding="utf-8") as f:
        f.write("# mq-definitions Validation Summary\n\n")
        f.write("| Type | Runtime | Documented | Missing | Stale | Status |\n")
        f.write("|------|---------|------------|---------|-------|--------|\n")
        for row in summary_rows:
            f.write("| {} | {} | {} | {} | {} | {} |\n".format(*row))

    print(f"Reports written to {REPORT_DIR}/")
    print(f"Summary: {REPORT_DIR}/_summary.md")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", action="store_true",
                        help="Read result JSON and generate markdown (run after Lua script)")
    args = parser.parse_args()

    cfg = load_config()

    if args.report:
        generate_reports(cfg)
        return

    if not cfg.mq_definitions_path:
        print("ERROR: mq_definitions_path not set in config.json")
        sys.exit(1)

    print(f"Parsing mq-definitions from {cfg.mq_definitions_path} ...")
    defs = parse_definitions(cfg.mq_definitions_path)
    print(f"  {len(defs)} types")

    lua_src = generate_lua(cfg, defs)
    out_path = cfg.mq_lua_path / SCRIPT_NAME
    out_path.write_text(lua_src, encoding="utf-8")
    print(f"Lua script written to: {out_path}")
    print()
    print("Next steps:")
    print(f"  1. /lua run validate-defs   (in-game — takes ~1 minute)")
    print(f"  2. python scripts/gen_validate_script.py --report")


if __name__ == "__main__":
    main()
