"""gen_validate_script.py

Generates a self-contained Lua validation script with mq-definitions data
baked in. The Lua script runs entirely in-game, compares each type's runtime
members against the embedded defs, and writes a JSON result file.

Usage:
    python gen_validate_script.py --defs PATH_TO_MQ_DEFINITIONS --lua PATH_TO_MQ_LUA
    python gen_validate_script.py --report --lua PATH_TO_MQ_LUA

Arguments:
    --defs   Path to mq-definitions repo root (contains mq/datatype/)
    --lua    Path to MacroQuest lua directory
    --report Read result JSON and generate markdown reports (run after Lua script)
"""

import argparse
import json
import re
from pathlib import Path
from typing import Optional

SCRIPT_NAME = "validate-defs.lua"
RESULT_NAME = "validate-defs-result.json"
REPORT_DIR  = Path(__file__).parent / "validation"

# ---------------------------------------------------------------------------
# LuaCATS parser — no external dependencies
# ---------------------------------------------------------------------------

_CLASS_RE = re.compile(r"^---@class\s+(\S+?)(?:\s*:\s*(\S+))?(?:\s|$)")
_FIELD_RE = re.compile(r"^---@field\s+(?:public\s+|protected\s+|private\s+)?(\S+)")


def _parse_file(path: Path) -> dict[str, tuple[set[str], Optional[str]]]:
    """Return {type_name_lower: (members, parent_name_lower)} from one file."""
    result: dict[str, tuple[set[str], Optional[str]]] = {}
    current_class: Optional[str] = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = _CLASS_RE.match(line)
        if m:
            current_class = m.group(1).lower()
            parent = m.group(2).lower() if m.group(2) else None
            if current_class not in result:
                result[current_class] = (set(), parent)
            continue
        m = _FIELD_RE.match(line)
        if m and current_class is not None:
            result[current_class][0].add(m.group(1).lower())
    return result


def parse_definitions(defs_path: Path) -> dict[str, set[str]]:
    """Parse mq/datatype/ LuaCATS files and return {type_name: {all_members}}.

    Inheritance is resolved: each type's member set includes all members from
    its ancestor types so that inherited members aren't flagged as missing.
    """
    # First pass: collect raw members and inheritance per type
    raw: dict[str, tuple[set[str], Optional[str]]] = {}
    datatype_dir = defs_path / "mq" / "datatype"
    if not datatype_dir.exists():
        raise FileNotFoundError(f"mq/datatype/ not found under {defs_path}")
    for lua_file in datatype_dir.rglob("*.lua"):
        for type_name, (members, parent) in _parse_file(lua_file).items():
            if type_name in raw:
                raw[type_name][0].update(members)
            else:
                raw[type_name] = (set(members), parent)

    # Second pass: resolve full member sets by walking inheritance chain
    def resolve(name: str, seen: set[str]) -> set[str]:
        if name not in raw or name in seen:
            return set()
        seen.add(name)
        members, parent = raw[name]
        all_members = set(members)
        if parent:
            all_members |= resolve(parent, seen)
        return all_members

    return {name: resolve(name, set()) for name in raw}


# ---------------------------------------------------------------------------
# Lua script generation
# ---------------------------------------------------------------------------

LUA_TEMPLATE = """\
-- validate-defs.lua
-- Auto-generated by gen_validate_script.py — do not edit.
-- Run with: /lua run validate-defs
--
-- Compares runtime MQ type members against baked-in mq-definitions data,
-- then writes results to validate-defs-result.json in the lua directory.

local mq = require('mq')

-- ---------------------------------------------------------------------------
-- Baked-in mq-definitions data: {type_name -> {member -> true}}
-- ---------------------------------------------------------------------------
local defs = {DEF_TABLE}

-- ---------------------------------------------------------------------------
-- Minimal JSON encoder
-- ---------------------------------------------------------------------------
local function je(v)
    local t = type(v)
    if t == 'string'  then return '"' .. v:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"') .. '"' end
    if t == 'boolean' then return tostring(v) end
    if t == 'number'  then return tostring(v) end
    if t == 'nil'     then return 'null' end
    if t == 'table' then
        if #v > 0 then
            local p = {}
            for _, x in ipairs(v) do p[#p+1] = je(x) end
            return '[' .. table.concat(p, ',') .. ']'
        else
            local p = {}
            for k, x in pairs(v) do p[#p+1] = je(tostring(k)) .. ':' .. je(x) end
            return '{' .. table.concat(p, ',') .. '}'
        end
    end
    return 'null'
end

-- ---------------------------------------------------------------------------
-- Scan and compare
-- ---------------------------------------------------------------------------
local results = {}
local type_list = {}
for k in pairs(defs) do type_list[#type_list+1] = k end
table.sort(type_list)

local total = #type_list
print(string.format('[validate-defs] Checking %d types...', total))

for idx, type_name in ipairs(type_list) do
    local def_members = defs[type_name]
    local tlo = mq.TLO.Type(type_name)

    if not tlo() then
        results[type_name] = { exists=false }
    else
        local runtime = {}
        local empty_run = 0
        for i = 0, 300 do
            local m = tlo.Member(i)()
            if m and m ~= '' then
                runtime[m:lower()] = true
                empty_run = 0
            else
                empty_run = empty_run + 1
                if empty_run >= 20 then break end
            end
        end

        local missing = {}
        for m in pairs(runtime) do
            if not def_members[m] then missing[#missing+1] = m end
        end
        table.sort(missing)

        local stale = {}
        for m in pairs(def_members) do
            if not runtime[m] then stale[#stale+1] = m end
        end
        table.sort(stale)

        local inherits = tlo.InheritedType and tlo.InheritedType() or nil
        local rc = 0; for _ in pairs(runtime) do rc = rc + 1 end
        local dc = 0; for _ in pairs(def_members) do dc = dc + 1 end

        results[type_name] = {
            exists        = true,
            runtime_count = rc,
            def_count     = dc,
            missing       = missing,
            stale         = stale,
            inherits      = (inherits and inherits ~= '') and inherits or nil,
        }
    end

    if idx % 10 == 0 then
        print(string.format('[validate-defs] %d/%d done', idx, total))
    end
    mq.delay(300)
end

-- ---------------------------------------------------------------------------
-- Write JSON output
-- ---------------------------------------------------------------------------
local out_path = mq.luaDir .. '/{result_name}'
local f, err = io.open(out_path, 'w')
if f then
    f:write(je(results))
    f:close()
    print('[validate-defs] Done! Results written to ' .. out_path)
    print('[validate-defs] Now run: python gen_validate_script.py --report --lua <path>')
else
    print('[validate-defs] ERROR writing output: ' .. tostring(err))
end
"""


def build_def_table(defs: dict[str, set[str]]) -> str:
    lines = ["{"]
    for type_name in sorted(defs):
        members = sorted(defs[type_name])
        if not members:
            continue
        member_str = ", ".join(f'["{m}"]=true' for m in members)
        lines.append(f'  ["{type_name}"] = {{{member_str}}},')
    lines.append("}")
    return "\n".join(lines)


def generate_lua(defs: dict, lua_dir: Path) -> str:
    script = LUA_TEMPLATE.replace("{DEF_TABLE}", build_def_table(defs))
    script = script.replace("{result_name}", RESULT_NAME)
    return script


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_reports(lua_dir: Path):
    result_path = lua_dir / RESULT_NAME
    if not result_path.exists():
        print(f"Result file not found: {result_path}")
        print("Run /lua run validate-defs in-game first.")
        return

    data = json.loads(result_path.read_text(encoding="utf-8"))
    REPORT_DIR.mkdir(exist_ok=True)

    summary_rows = []

    for type_name in sorted(data):
        info = data[type_name]

        if not info.get("exists", True):
            continue  # skip types not registered at runtime

        md_path = REPORT_DIR / f"{type_name}.md"
        inherits      = info.get("inherits")
        runtime_count = info.get("runtime_count", 0)
        def_count     = info.get("def_count", 0)
        missing       = info.get("missing") or []
        stale         = info.get("stale") or []
        matched       = runtime_count - len(missing)

        with md_path.open("w", encoding="utf-8") as f:
            f.write(f"# {type_name}\n\n")
            f.write(f"[← Summary](_summary.md)\n\n")
            if inherits:
                f.write(f"**Inherits:** `{inherits}`\n\n")
            f.write("| | Count |\n|---|---|\n")
            f.write(f"| Runtime members | {runtime_count} |\n")
            f.write(f"| Documented members | {def_count} |\n")
            f.write(f"| Matched | {matched} |\n")
            f.write(f"| Missing from defs | {len(missing)} |\n")
            f.write(f"| Stale in defs | {len(stale)} |\n\n")
            if missing:
                f.write("## Missing from mq-definitions\n\n")
                f.write("In-game but no `@field` in the definitions.\n\n")
                for m in missing:
                    f.write(f"- `{m}`\n")
                f.write("\n")
            if stale:
                f.write("## Stale in mq-definitions\n\n")
                f.write("`@field` entries in definitions not found at runtime.\n\n")
                for m in stale:
                    f.write(f"- `{m}`\n")
                f.write("\n")
            if not missing and not stale:
                f.write("> All documented members matched at runtime.\n\n")

        summary_rows.append((
            type_name, runtime_count, def_count,
            len(missing), len(stale),
            "🟢 ok" if not missing and not stale else "🟠 gaps"
        ))

    summary_path = REPORT_DIR / "_summary.md"
    with summary_path.open("w", encoding="utf-8") as f:
        f.write("# mq-definitions Validation Summary\n\n")
        f.write("| Type | Runtime | Documented | Missing | Stale | Status |\n")
        f.write("|------|---------|------------|---------|-------|--------|\n")
        for type_name, runtime, documented, missing, stale, status in summary_rows:
            f.write(f"| [{type_name}]({type_name}.md) | {runtime} | {documented} | {missing} | {stale} | {status} |\n")

    print(f"Reports written to {REPORT_DIR}/")
    print(f"Summary: {REPORT_DIR}/_summary.md")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--defs", metavar="PATH",
                        help="Path to mq-definitions repo root (required for --generate)")
    parser.add_argument("--lua", metavar="PATH", required=True,
                        help="Path to MacroQuest lua directory")
    parser.add_argument("--report", action="store_true",
                        help="Generate markdown reports from existing result JSON")
    args = parser.parse_args()

    lua_dir = Path(args.lua)

    if args.report:
        generate_reports(lua_dir)
        return

    if not args.defs:
        parser.error("--defs is required when generating the Lua script")

    defs_path = Path(args.defs)
    print(f"Parsing mq-definitions from {defs_path} ...")
    defs = parse_definitions(defs_path)
    print(f"  {len(defs)} types")

    lua_src = generate_lua(defs, lua_dir)
    out_path = lua_dir / SCRIPT_NAME
    out_path.write_text(lua_src, encoding="utf-8")
    print(f"Lua script written to: {out_path}")
    print()
    print("Next steps:")
    print(f"  1. /lua run validate-defs        (in-game — ~1 minute)")
    print(f"  2. python gen_validate_script.py --report --lua {args.lua}")


if __name__ == "__main__":
    main()
